apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-creator-list
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-creator-list-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: jobs-creator-list
  apiGroup: rbac.authorization.k8s.io
